language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key: e92d036e275958c01d1a342f577ca959540f8014
  file: MusiCraft.jar
  skip_cleanup: true
  on:
    tags: true
addons:
  sonarcloud:
    organization: "doggycraftdk"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DoggyCraftDK_MusiCraft	