name: MusiCraft
main: mc.holagrimola.MusiCraft
version: 0.5.1
description: Adding instruments to your server!
author: Holagrimola
api-version: 1.14
commands:
  musicraft:
    usage: /<command>
    description: The main command for the MusiCraft plugin.
  mc:
    usage: /<command>
    description: The main command for the MusiCraft plugin.